<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q1T02RD" failures="2" tests="4" name="TestRunFailedTC" time="1.277" errors="0" timestamp="2022-06-01T01:11:20 IST">
  <testcase classname="com.TestNG08runFailedTC01.FailedTC01" name="testCase1" time="0.034">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at com.TestNG08runFailedTC01.FailedTC01.testCase1(FailedTC01.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCase1 -->
  <testcase classname="com.TestNG08runFailedTC01.FailedTC01" name="testCase2" time="0.007">
    <failure type="graphql.AssertException" message="condition expected to be true">
      <![CDATA[graphql.AssertException: condition expected to be true
at graphql.Assert.assertTrue(Assert.java:85)
at com.TestNG08runFailedTC01.FailedTC01.testCase2(FailedTC01.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCase2 -->
  <testcase classname="com.TestNG08runFailedTC01.FailedTC02" name="testCase3" time="0.023"/>
  <testcase classname="com.TestNG08runFailedTC01.FailedTC02" name="testCase4" time="0.006"/>
</testsuite> <!-- TestRunFailedTC -->
