<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-Q1T02RD" failures="2" tests="8" name="RetryMultipleFailedTest:RunTime" time="0.188" errors="0" timestamp="2022-03-30T00:43:38 IST">
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test1" time="0.03">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test1" time="0.003">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test1" time="0.005">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test1" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG_4_myTests.MyTests_2_RunTime.Test1(MyTests_2_RunTime.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test2" time="0.008">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test2" time="0.003">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase classname="testNG_4_myTests.MyTests_2_RunTime" name="Test2" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNG_4_myTests.MyTests_2_RunTime.Test2(MyTests_2_RunTime.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
</testsuite> <!-- RetryMultipleFailedTest:RunTime -->
